export const dataPengurus = [
  { no: 1, nama: "Asykar Munadhil Syabib Irnowo", kelas: "8A1", jabatan: "Ketua BEST OSIS" },
  { no: 2, nama: "Ikhsan Ramadhan Kusnadi", kelas: "8A1", jabatan: "Wakil ketua BEST OSIS" },
  { no: 3, nama: "Hafidzah Bequina Aghniya A.", kelas: "8B2", jabatan: "Sekretaris" },
  { no: 4, nama: "Lulu Fatin Nabila", kelas: "8B2", jabatan: "Bendahara" },
  { no: 5, nama: "Kayla Azka Shazia Wibowo", kelas: "8B2", jabatan: "Mentri Dept. Humas" },
  { no: 6, nama: "Kayyasa Syalabiyyah Purnomosidi", kelas: "8B1", jabatan: "Anggota" },
  { no: 7, nama: "Athaya Zahratus Silmi", kelas: "8B1", jabatan: "Wakil Mentri Dept. Humas" },
  { no: 8, nama: "Alleira Aydina Nadifa S.", kelas: "7B2", jabatan: "Anggota" },
  { no: 9, nama: "Tsabita Nur Azizah", kelas: "7B2", jabatan: "Anggota" },
  { no: 10, nama: "Kirania Maiza", kelas: "8B1", jabatan: "Mentri Dept. Disorkes" },
  { no: 11, nama: "Shakila Hana Azzahra", kelas: "8B2", jabatan: "Anggota" },
  { no: 12, nama: "Almira Qanita Farzani Wakhid", kelas: "8B2", jabatan: "Anggota" },
  { no: 13, nama: "Dimarsyah Daanish Hafiz", kelas: "7A1", jabatan: "Anggota" },
  { no: 14, nama: "Muhammad Razka Thariq A.", kelas: "8A1", jabatan: "Wakil Mentri Dept. Disorkes" },
  { no: 15, nama: "Muhammad Ichigo Ararie Putra", kelas: "8A2", jabatan: "Mentri Dept. SABDA" },
  { no: 16, nama: "Alya Ulfa", kelas: "8B2", jabatan: "Wakil Mentri Dept. SABDA" },
  { no: 17, nama: "Sahla Abira Syufie", kelas: "8B1", jabatan: "Anggota" },
  { no: 18, nama: "Aruni Khaira Sabila", kelas: "8B1", jabatan: "Anggota" },
  { no: 19, nama: "Dastian Al Qassimy", kelas: "7A2", jabatan: "Anggota" },
  { no: 20, nama: "Muhammad Roffiq musaffa", kelas: "8A1", jabatan: "Mentri Dept. Agama" },
  { no: 21, nama: "Mazaya Nairuwa A.", kelas: "8B2", jabatan: "Wakil Mentri Dept. Agama" },
  { no: 22, nama: "Hafy Aydin Ramaputra", kelas: "7A1", jabatan: "Anggota" },
  { no: 23, nama: "Arkaan Raffaizaz A.", kelas: "7A2", jabatan: "Anggota" },
  { no: 24, nama: "Arfa Syazia Bisyri", kelas: "8B1", jabatan: "Anggota" },
  { no: 25, nama: "Muhammad Zuhair Asyraf", kelas: "8A2", jabatan: "Mentri Dept. Lingkup" },
  { no: 26, nama: "Atiqah Fauziyah Rahma", kelas: "8B1", jabatan: "Wakil Mentri Dept. Lingkup" },
  { no: 27, nama: "Arvina Andya Putri", kelas: "8B1", jabatan: "Anggota" },
  { no: 28, nama: "Annisa Mutmainah Arifin", kelas: "7B2", jabatan: "Anggota" },
  { no: 29, nama: "Ibamez Arsyad Zamzami", kelas: "7A1", jabatan: "Anggota" },
  { no: 30, nama: "Almarzuq Ramadhan Qoimudin", kelas: "8A1", jabatan: "Mentri Dept. IPTEK" },
  { no: 31, nama: "Fairuz Azzahra M", kelas: "8B1", jabatan: "Wakil Mentri Dept. IPTEK" },
  { no: 32, nama: "Devdan Abyaz Rasyad", kelas: "7A1", jabatan: "Anggota" },
  { no: 33, nama: "Intan Fitri Mahrizal", kelas: "8B2", jabatan: "Anggota" },
  { no: 34, nama: "Safira Azkadina Ardiyanti", kelas: "7B2", jabatan: "Anggota" },
];

export const processedUsers = dataPengurus.map(u => ({
  ...u,
  password: `${u.kelas.charAt(0)}${String(u.no).padStart(3, '0')}`,
  gender: u.kelas.includes('A') ? 'Laki-laki' : 'Perempuan',
  role: ["Ketua", "Wakil", "Sekretaris", "Bendahara"].some(r => u.jabatan.includes(r)) ? 'Admin' : 'Pengurus',
  poin: 0
}));
